import type { Category, Order, Product, StoreSettings } from "@/lib/types";
import { defaultStoreMode } from "@/lib/store-mode";

export const demoCategories: Category[] = [
  { name: "Personalized", slug: "personalized", description: "Names, notes, and custom details made personal.", color: "#7a3e3e", featured: true, active: true },
  { name: "For Her", slug: "for-her", description: "Soft, useful, and considered gifts.", color: "#9a6b5b", featured: true, active: true },
  { name: "For Him", slug: "for-him", description: "Clean, practical pieces with lasting use.", color: "#59614a", featured: true, active: true },
  { name: "Celebrations", slug: "celebrations", description: "Ready pieces for birthdays, milestones, and events.", color: "#8b7a62", featured: true, active: true },
];

export const demoProducts: Product[] = [
  {
    slug: "memory-lane-photo-frame",
    name: "Memory Lane Photo Frame",
    shortDescription: "A layered keepsake frame made around your favorite moment.",
    description: "Send us your photo and message. We compose, print, and finish every frame by hand before sharing a preview with you on WhatsApp.",
    price: 1299,
    compareAtPrice: 1599,
    category: "personalized",
    images: ["https://images.unsplash.com/photo-1602173574767-37ac01994b2a?auto=format&fit=crop&w=1200&q=85"],
    tags: ["bestseller", "anniversary"],
    featured: true,
    active: true,
    customizable: true,
    stock: 18,
  },
  {
    slug: "sunshine-gift-box",
    name: "Sunshine Gift Box",
    shortDescription: "A bright box of little joys for instant good moods.",
    description: "A ready-to-gift edit with a candle, treats, a keepsake card, and cheerful details. Contents may vary slightly by season.",
    price: 1799,
    category: "for-her",
    images: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1200&q=85"],
    tags: ["birthday", "ready-to-gift"],
    featured: true,
    active: true,
    customizable: true,
    stock: 12,
  },
  {
    slug: "desk-reset-kit",
    name: "Desk Reset Kit",
    shortDescription: "Useful, handsome desk pieces packed as a thoughtful reset.",
    description: "A practical gift for new roles, new offices, or anyone who deserves a tidier workday.",
    price: 1499,
    category: "for-him",
    images: ["https://images.unsplash.com/photo-1513883049090-d0b7439799bf?auto=format&fit=crop&w=1200&q=85"],
    tags: ["work", "minimal"],
    featured: true,
    active: true,
    customizable: false,
    stock: 9,
  },
  {
    slug: "celebration-mini-hamper",
    name: "Celebration Mini Hamper",
    shortDescription: "Small in size, properly celebratory in spirit.",
    description: "An easy crowd-pleaser with sweet treats, confetti details, and your handwritten note.",
    price: 999,
    category: "celebrations",
    images: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&w=1200&q=85"],
    tags: ["quick-gift", "birthday"],
    featured: false,
    active: true,
    customizable: true,
    stock: 25,
  },
  {
    slug: "custom-name-tumbler",
    name: "Custom Name Tumbler",
    shortDescription: "A daily-use tumbler personalized with their name.",
    description: "Choose the name and share your color preference at checkout. We confirm the final design before making it.",
    price: 799,
    category: "personalized",
    images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1200&q=85"],
    tags: ["personalized", "useful"],
    featured: false,
    active: true,
    customizable: true,
    stock: 30,
  },
  {
    slug: "slow-sunday-candle-duo",
    name: "Slow Sunday Candle Duo",
    shortDescription: "Two comforting scents for softer evenings.",
    description: "A pair of hand-poured candles in reusable glass jars, packed in our signature gift wrap.",
    price: 1199,
    category: "for-her",
    images: ["https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=85"],
    tags: ["home", "calm"],
    featured: false,
    active: true,
    customizable: false,
    stock: 14,
  },
];

const demoStoreMode = defaultStoreMode();

export const demoSettings: StoreSettings = {
  whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "919999999999",
  shippingFee: 99,
  freeShippingThreshold: 1999,
  announcement: demoStoreMode === "bulk" ? "Bulk gifting quotes are confirmed on WhatsApp" : "Free shipping on orders above ₹1,999",
  storeMode: demoStoreMode,
};

export const demoOrders: Order[] = [
  {
    orderNumber: "ORD-260614-A1B2",
    items: [{ key: demoProducts[0].slug, slug: demoProducts[0].slug, name: demoProducts[0].name, price: demoProducts[0].price, images: demoProducts[0].images, customizable: demoProducts[0].customizable, quantity: 1 }],
    customer: {
      name: "Demo Customer",
      phone: "9999999999",
      address: "12 Sample Street",
      city: "Mumbai",
      postalCode: "400001",
      occasion: "Anniversary",
    },
    subtotal: 1299,
    shipping: 99,
    total: 1398,
    status: "new",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
